import React, { useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { getExamById } from '../data/exams.js'
import { subjects as quizSubjects } from '../data/quizzes.js'
import { upscMock01 } from '../data/upscMock01.js'
import { sscCglMock01 } from '../data/sscCglMock01.js'
import { sscCglMocks02to10 } from '../data/sscCglMocks02to10.js'
import { getExamMock } from '../data/examMocks.js'
import { getExamMockStandard } from '../data/examMockStandards.js'
import { useApp } from '../context/AppContext.jsx'
import AdSlot from '../components/AdSlot.jsx'
import NotFound from './NotFound.jsx'

const tabs=[{id:'overview',label:'Overview',icon:'fa-circle-info'},{id:'pattern',label:'Exam Pattern',icon:'fa-list-ol'},{id:'syllabus',label:'Syllabus',icon:'fa-book'},{id:'strategy',label:'Strategy',icon:'fa-chess'},{id:'practice',label:'Practice',icon:'fa-pen'}]

export default function ExamDetails(){
 const {examId}=useParams(); const navigate=useNavigate(); const exam=getExamById(examId); const [tab,setTab]=useState('overview'); const {updateProfile,profile}=useApp(); const examMock=getExamMock(examId); const mockStandard=getExamMockStandard(examId)
 if(!exam)return <NotFound />
 const isSelected=profile.selectedExam===exam.id
 const isSscCgl=exam.id==='ssc-cgl'
 const mocks=isSscCgl?[sscCglMock01,...sscCglMocks02to10]:null
 const mock=exam.id==='upsc-cse'?upscMock01:isSscCgl?sscCglMock01:examMock
 const openMock=(selectedMock)=>{if(!selectedMock?.questions?.length)return;const targetQuestions=mockStandard?.questions;const isFullLength=Number.isInteger(targetQuestions)?selectedMock.questions.length>=targetQuestions:false;const scoring=mockStandard?.scoring||null;const negativeMarking=Number.isFinite(Number(scoring?.wrong))?Math.abs(Number(scoring.wrong)):0;const sectionTimers=mockStandard?.sections?.filter((section)=>Number.isFinite(Number(section.minutes))&&Number(section.questions)>0).map((section)=>({name:section.name,questions:Number(section.questions),minutes:Number(section.minutes)}))||[];navigate('/quiz/play',{state:{questions:selectedMock.questions,title:selectedMock.title,subject:exam.name,examName:exam.name,mixed:true,duration:mockStandard?.duration||selectedMock.duration||30,fullLength:isFullLength,scoring,negativeMarking,sectionTimers,examStandard:mockStandard||null}})}
 return <div className="space-y-5 -mt-1">
  <div className={`rounded-2xl p-5 bg-gradient-to-br ${exam.color} text-white relative overflow-hidden`}><div className="flex items-start justify-between"><div><h1 className="text-2xl font-extrabold">{exam.name}</h1><p className="text-sm text-white/85">{exam.fullName}</p><p className="text-xs text-white/70 mt-2 max-w-md">{exam.tagline}</p></div><div className="w-14 h-14 rounded-2xl bg-white/20 flex items-center justify-center text-2xl shrink-0"><i className={`fas ${exam.icon}`}></i></div></div><button onClick={()=>updateProfile({selectedExam:isSelected?null:exam.id})} className={`mt-4 text-xs font-semibold px-3 py-1.5 rounded-full ${isSelected?'bg-white text-primary-700':'bg-white/20 text-white'}`}><i className={`fas ${isSelected?'fa-check':'fa-plus'} mr-1`}></i>{isSelected?'Selected as your goal':'Set as my target exam'}</button></div>
  <div className="flex gap-2 overflow-x-auto pb-1 -mx-4 px-4 md:mx-0 md:px-0">{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-full text-sm font-medium transition ${tab===t.id?'bg-primary-600 text-white':'bg-white dark:bg-slate-900 text-slate-500 dark:text-slate-400 border border-slate-200 dark:border-slate-700'}`}><i className={`fas ${t.icon} text-xs`}></i>{t.label}</button>)}</div>
  {tab==='overview'&&<div className="space-y-4"><InfoCard title="Eligibility" icon="fa-user-check"><InfoRow label="Education" value={exam.eligibility.education}/><InfoRow label="Nationality" value={exam.eligibility.nationality}/>{exam.eligibility.other&&<InfoRow label="Other" value={exam.eligibility.other}/>}</InfoCard><InfoCard title="Age Limit" icon="fa-cake-candles"><InfoRow label="General" value={exam.ageLimit.general}/><InfoRow label="Relaxation" value={exam.ageLimit.relaxation}/></InfoCard><InfoCard title="Posts / Wings" icon="fa-briefcase"><div className="flex flex-wrap gap-2">{exam.posts.map(p=><span key={p} className="badge bg-primary-50 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300">{p}</span>)}</div></InfoCard><InfoCard title="Important Topics" icon="fa-star"><div className="flex flex-wrap gap-2">{exam.importantTopics.map(t=><span key={t} className="badge bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300">{t}</span>)}</div></InfoCard><a href={exam.officialLink} target="_blank" rel="noopener noreferrer" className="btn-outline w-full"><i className="fas fa-arrow-up-right-from-square"></i> Visit Official Website</a></div>}
  {tab==='pattern'&&<div className="space-y-3">{exam.examPattern.map((stage,i)=><div key={i} className="card p-4"><div className="flex items-center gap-2 mb-2"><span className="w-7 h-7 rounded-full bg-primary-600 text-white text-xs font-bold flex items-center justify-center shrink-0">{i+1}</span><h3 className="font-bold text-sm">{stage.stage}</h3></div><div className="flex gap-4 text-xs text-slate-400 mb-2 ml-9"><span><i className="fas fa-desktop mr-1"></i>{stage.mode}</span><span><i className="fas fa-clock mr-1"></i>{stage.duration}</span></div><p className="text-sm text-slate-600 dark:text-slate-300 ml-9">{stage.details}</p></div>)}</div>}
  {tab==='syllabus'&&<div className="space-y-3"><p className="text-sm text-slate-500 dark:text-slate-400">Subjects: <span className="font-medium text-slate-700 dark:text-slate-200">{exam.subjects.join(', ')}</span></p>{Object.entries(exam.syllabus).map(([subject,topics])=><SyllabusAccordion key={subject} subject={subject} topics={topics}/>)}</div>}
  {tab==='strategy'&&<div className="space-y-3"><div className="card p-4"><h3 className="font-bold text-sm mb-3"><i className="fas fa-chess-knight text-primary-500 mr-2"></i>Preparation Strategy</h3><ol className="space-y-2.5">{exam.strategy.map((s,i)=><li key={i} className="flex gap-3 text-sm text-slate-600 dark:text-slate-300"><span className="w-6 h-6 rounded-full bg-primary-50 dark:bg-primary-900/30 text-primary-600 dark:text-primary-400 text-xs font-bold flex items-center justify-center shrink-0">{i+1}</span>{s}</li>)}</ol></div><Link to="/planner" state={{examName:exam.name}} className="btn-primary w-full"><i className="fas fa-calendar-days"></i> Create a study plan for {exam.name}</Link></div>}
  {tab==='practice'&&<div className="space-y-4"><div className="card p-4"><h3 className="font-bold text-sm mb-3"><i className="fas fa-pen text-primary-500 mr-2"></i>Practice Section</h3><p className="text-sm text-slate-500 dark:text-slate-400 mb-3">Sharpen your skills with subject-wise practice quizzes relevant to {exam.name}.</p><div className="grid grid-cols-2 gap-2">{quizSubjects.map(s=><Link key={s.id} to={`/quiz?subject=${s.id}`} className="card card-hover p-3 flex items-center gap-2"><div className={`w-8 h-8 rounded-lg ${s.color} flex items-center justify-center text-white text-xs shrink-0`}><i className={`fas ${s.icon}`}></i></div><span className="text-xs font-medium">{s.name}</span></Link>)}</div></div>
   {mocks?<div className="space-y-3"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold text-sm">SSC CGL Tier-I Full Mock Series</h3><p className="text-xs text-slate-400 mt-1">10 full-length mocks • 100 questions each • answers + explanations</p></div><span className="badge bg-emerald-100 text-emerald-700">10 MOCKS</span></div>{mocks.map(paper=><div key={paper.id||paper.title} className="card p-4 border border-indigo-100 dark:border-indigo-900/50 bg-gradient-to-br from-indigo-50 to-white dark:from-indigo-950/40 dark:to-slate-900"><div className="flex items-start gap-3"><div className="w-11 h-11 rounded-xl bg-indigo-600 text-white flex items-center justify-center shrink-0"><i className="fas fa-file-circle-check"></i></div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-bold text-sm">{paper.title}</h3><span className="badge bg-emerald-100 text-emerald-700">FULL MOCK</span></div><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{paper.questions.length} questions • 200 marks • 60 min • −0.50 wrong answer • answers + explanations</p><button onClick={()=>openMock(paper)} className="btn-primary inline-flex mt-3"><i className="fas fa-book-open"></i> Open Mock</button></div></div></div>)}</div>:<div className="card p-4 border border-indigo-100 dark:border-indigo-900/50 bg-gradient-to-br from-indigo-50 to-white dark:from-indigo-950/40 dark:to-slate-900"><div className="flex items-start gap-3"><div className="w-11 h-11 rounded-xl bg-indigo-600 text-white flex items-center justify-center shrink-0"><i className="fas fa-file-circle-check"></i></div><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-bold text-sm">{mock?.title||`${exam.name} Practice Mock 01`}</h3><span className="badge bg-amber-100 text-amber-700">PRACTICE SET</span></div><p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{mock?.questions?.length||0} questions • answers • explanations</p><button onClick={()=>openMock(mock)} disabled={!mock?.questions?.length} className="btn-primary inline-flex mt-3 disabled:opacity-50"><i className="fas fa-book-open"></i> Open Mock</button></div></div></div>}
   <AdSlot label="Sponsored Practice Material"/></div>}
 </div>
}
function InfoCard({title,icon,children}){return <div className="card p-4"><h3 className="font-bold text-sm mb-3"><i className={`fas ${icon} text-primary-500 mr-2`}></i>{title}</h3><div className="space-y-2">{children}</div></div>}
function InfoRow({label,value}){return <div><p className="text-xs text-slate-400 font-medium">{label}</p><p className="text-sm text-slate-600 dark:text-slate-300">{value}</p></div>}
function SyllabusAccordion({subject,topics}){const [open,setOpen]=useState(false);return <div className="card overflow-hidden"><button onClick={()=>setOpen(!open)} className="w-full flex items-center justify-between p-4"><span className="font-semibold text-sm">{subject}</span><i className={`fas fa-chevron-down text-slate-400 text-xs transition-transform ${open?'rotate-180':''}`}></i></button>{open&&<div className="px-4 pb-4 flex flex-wrap gap-2">{topics.map(t=><span key={t} className="badge bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">{t}</span>)}</div>}</div>}
